export const FECTH_BOARDS_REQUEST = 'FECTH_BOARDS_REQUEST'
export const FECTH_BOARDS_SUCCESS = 'FECTH_BOARDS_SUCCESS'
export const FECTH_BOARDS_FAILURE = 'FECTH_BOARDS_FAILURE'

export const FECTH_LISTS_REQUEST = 'FECTH_LISTS_REQUEST'
export const FECTH_LISTS_SUCCESS = 'FECTH_LISTS_SUCCESS'
export const FECTH_LISTS_FAILURE = 'FECTH_LISTS_FAILURE'

export const FECTH_TASKS_REQUEST = 'FECTH_TASKS_REQUEST'
export const FECTH_TASKS_SUCCESS = 'FECTH_TASKS_SUCCESS'
export const FECTH_TASKS_FAILURE = 'FECTH_TASKS_FAILURE'

export const ADD_BOARD = 'ADD_BOARD'
export const ADD_COLUMN = 'ADD_COLUMN'
export const ADD_TASK = 'ADD_TASK'
export const DELETE_TASK = 'DELETE_TASK'
export const MARK_AS_COMPLETED = 'MARK_AS_COMPLETED'
